# Generated by Django 5.0.6 on 2024-08-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_worker_department_resource_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_depends_on_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_task_dependencies', to='account.task')),
                ('second_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_task_dependencies', to='account.task')),
            ],
            options={
                'ordering': ['first_task', 'second_task'],
                'unique_together': {('first_task', 'second_task')},
            },
        ),
    ]
